sudo: required
dist: trusty

services:
  - docker

matrix:
  include:
    - language: java
      jdk: openjdk11
      if: (branch == master OR branch == main)
      script:
        - ./gradlew build
        - docker build -t demo-backend:latest .
      before_script:
        - cd ./travis-test/

    - language: node_js
      node_js: stable
      if: (branch = master OR branch == main)
      install:
        - npm install
      before_install:
        - cd ./fr/
      script:
        - npm run build
        - docker build -t demo-frontend:latest .

